### ISSUE TITLE
login page re design

### ISSUE THREAD

**Issue by TheLoneAlchemist** [TheLoneAlchemist/MoodMusic#2]
you can re design login page with any language

**Comment by sattya19** [comment]
can you please assign this to me

**Comment by princyballabh** [comment]
Hey, i have knowledge about html and css. I would like to re-design the login page

**Comment by princyballabh** [comment]
Do check my PR!

**Comment by therefat** [comment]
> you can re design login page with any language

yes please explain detail

**Comment by TheLoneAlchemist** [comment]
> Do check my PR!

I have approved your pull request.

**Comment by TheLoneAlchemist** [comment]
> can you please assign this to me

Checkout the new issue

**Comment by TheLoneAlchemist** [comment]
> > you can re design login page with any language
> 
> yes please explain detail

You can design a navbar for this; That would be great.

**Comment by TheLoneAlchemist** [comment]
> can you please assign this to me

you can work on this:
**_[https://github.com/TheLoneAlchemist/MoodMusic/issues/4](https://github.com/TheLoneAlchemist/MoodMusic/issues/4)_**
Just comment there I will assign that to you.
